pekko.http.server.idle-timeout = infinite
pekko.http.client.idle-timeout = infinite

frontend.devUrl = "http://localhost:5173"

play.filters.csrf.exempt-paths = [
  "/api/.*"
]

play.filters.disabled += "play.filters.csrf.CSRFFilter"
%dev.play.filters.disabled += "play.filters.csrf.CSRFFilter"

# CORS
play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  allowedOrigins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://wizard-web-328e8013cfd8.herokuapp.com"
  ]


  allowedHttpMethods = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

  allowedHttpHeaders = [
    "Accept",
    "Content-Type",
    "Csrf-Token",
    "X-Requested-With",
    "Authorization"
  ]

  allowCredentials = true
  preflightMaxAge = 1 minute
}

play.filters.hosts {
  allowed = ["wizard-web-328e8013cfd8.herokuapp.com"]
  # allowed = ["*"]
}
