pekko.http.server.idle-timeout = infinite
pekko.http.client.idle-timeout = infinite

frontend.devUrl = "http://localhost:5173"

play.filters.csrf.exempt-paths = [
  "/api/.*"
]

play.filters.disabled += "play.filters.csrf.CSRFFilter"

%dev.play.filters.disabled += "play.filters.csrf.CSRFFilter"

play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  allowedOrigins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173"
  ]

  allowedHttpMethods = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]

  allowedHttpHethataders = [
    "Accept",
    "Content-Type",
    "Csrf-Token",
    "X-Requested-With",
    "Authorization"
  ]

  allowCredentials = true

  preflightMaxAge = 1 minute
}

silhouette {
  # Authentication
  authenticator.cookieName="id"
  authenticator.cookiePath="/"
  authenticator.secureCookie=false
  authenticator.httpOnlyCookie=true
  authenticator.useFingerprinting=true
  authenticator.authenticatorIdleTimeout=30 minutes
  authenticator.authenticatorExpiry=12 hours

  authenticator.signer.key = "kEqvfMqcorwUUNBZhzOXqPuwwfkrFlBg"
  authenticator.crypter.key = "wCyGJTYgmMZWauylDCXfcuUKxSsLEZUX"
}
